spring:
  profiles:
    include: local
#인크루드 역활 알아봐서 찾아낸 뒤 공유하기.
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
#       ddl-auto: validate
      show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/Develop/Github/SpringBlogExam/test_db;AUTO_SERVER=TRUE
    username: root
    password: 1367
    validation-query: SELECT 1
  h2:
    console:
      enabled: true
      path: /h2-console