spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
      #      ddl-auto: validate
    show-sql: true

  datasource:
    url: jdbc:h2:~/mesvie;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    validation-query: SELECT 1
  devtools:
    livereload:
      enabled: true # 정적파일들의 실시간 갱신

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.type: trace


